In [21]:
'hello'

'hello'

In [22]:
import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import os


stem = PorterStemmer()

In [23]:
print(os.getcwd())  # current working directory
print(os.path.exists('data/raw/spam.csv'))

f:\Project\Spam Classifer\notebook
False

In [24]:
df = pd.read_csv(r'F:\Project\Spam Classifer\data\raw\spam.csv', encoding='latin1')
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True, errors='ignore')
df = df.rename(columns={'v1': 'category', 'v2': 'Message'})
df.head()

  category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [25]:
df.isna().sum()

category    0
Message     0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(403)

In [27]:
df.shape

(5572, 2)

In [28]:
df.drop_duplicates(inplace= True)

In [29]:
df.shape

(5169, 2)

In [30]:
stop_words = set(stopwords.words('english'))

In [31]:
def preprocess_text(text):
    # 1. Lowercase
    text = text.lower()

    text = re.sub(r'https?://\S+|www\.\S+', 'URL_TOKEN', text) # Mark URLs instead of deleting
    text = re.sub(r'[^\w\s]', 'SYM_TOKEN', text) # Mark punctuation/symbols instead of deleting
    text = re.sub(r'\d+', 'NUM_TOKEN', text)
    # 2. Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    # 3. Remove special quotes and HTML tags
    text = re.sub(r"[‘’“”«»]", "", text)
    text = re.sub(r'<.*?>', '', text)
    # 4. Remove digits
    text = re.sub(r'\d+', '', text)
    # 5. Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # 6. Tokenize
    words = word_tokenize(text)
    # 7. Remove stopwords & Stemming
    words = [stem.stem(word) for word in words if word not in stop_words]
    
    return " ".join(words)

In [32]:
df['Message'] = df['Message'].apply(preprocess_text)

In [33]:
df.head()

  category                                            Message
0      ham  go jurong pointsymtoken crazysymtokensymtoken ...
1      ham  ok larsymtokensymtokensymtoken joke wif u onis...
2     spam  free entri numtoken wkli comp win fa cup final...
3      ham  u dun say earli horsymtokensymtokensymtoken u ...
4      ham  nah donsymtok think goe usfsymtoken live aroun...

In [34]:
import os

print(os.getcwd())

f:\Project\Spam Classifer\notebook

In [35]:
df.to_csv('../data/processed/cleaned_data.csv', index= False)